language: csharp
solution: .sln
install:
  - nuget restore FindWordsWithConcatenations.sln
  - nuget install NUnit.Runners -Version 3.5.0 -OutputDirectory testrunner
script:
  - xbuild  /p:Configuration=Debug ./FindWordsWithConcatenations.sln
  - mono ./testrunner/NUnit.ConsoleRunner.3.5.0/tools/nunit-agent.exe ./TestFindWordsWithConcatenations/bin/Debug/TestFindWordsWithConcatenations.dll